// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {core} from '../models';

export function AppInfo():Promise<core.ResponseData>;

export function Config():Promise<core.ResponseData>;

export function FileExists(arg1:string):Promise<boolean>;

export function ResetApp():Promise<void>;
